// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ToolCall } from "./ToolCall";

export type Block = { "type": "text", text: string, } | { "type": "thinking", text: string, } | { "type": "toolCall" } & ToolCall;
