// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Estimated USD cost split by token kind; parts sum to the matching cost_usd.
 */
export type CostBreakdown = { input: number, output: number, cacheRead: number, cacheWrite: number, };
