// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DayPoint } from "./DayPoint";

/**
 * A precomputed daily series for a provider, model, or project.
 */
export type DailySeries = { key: string, label: string, 
/**
 * Only days with data, sorted by date.
 */
points: Array<DayPoint>, };
