// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Inclusive day range in the machine's local timezone, `YYYY-MM-DD`. `None` means unbounded.
 */
export type DateRange = { from?: string, to?: string, };
