// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CostBreakdown } from "./CostBreakdown";
import type { Usage } from "./Usage";

export type DayBucket = { 
/**
 * `YYYY-MM-DD`. Every day in the range is present, including empty ones.
 */
date: string, sessions: number, toolCalls: number, 
/**
 * Tool calls that ended in error that day. Absent means zero.
 */
toolErrors?: number, usage: Usage, costUsd: number, costBreakdown: CostBreakdown, 
/**
 * Tokens from models without a known price. Absent means zero.
 */
unpricedTokens?: number, };
