// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One day in a compact, message-attributed daily series.
 */
export type DayPoint = { 
/**
 * `YYYY-MM-DD` in the machine's local timezone.
 */
date: string, costUsd: number, tokens: number, activeMs: number, sessions: number, toolCalls: number, 
/**
 * Tool calls that ended in error that day. Absent means zero.
 */
toolErrors?: number, messages: number, };
