// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CostBreakdown } from "./CostBreakdown";
import type { Usage } from "./Usage";

export type GroupBucket = { 
/**
 * Grouping key: project path, model id, etc.
 */
key: string, 
/**
 * Human label (e.g. project name).
 */
label: string, sessions: number, usage: Usage, costUsd: number, costBreakdown: CostBreakdown, 
/**
 * Tokens from models without a known price. Absent means zero.
 */
unpricedTokens?: number, };
