// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Compact message and session counts for each local weekday/hour cell.
 */
export type HourlyActivity = { 
/**
 * Monday is 0 and Sunday is 6.
 */
weekday: number, hour: number, messages: number, 
/**
 * Distinct sessions with at least one message in this cell.
 */
sessions: number, };
