// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Block } from "./Block";
import type { Role } from "./Role";
import type { Usage } from "./Usage";

export type Message = { id: string, role: Role, timestamp: string, 
/**
 * Model that produced the message (assistant only).
 */
model: string | null, blocks: Array<Block>, 
/**
 * Usage of this API message (assistant only).
 */
usage: Usage | null, 
/**
 * Discarded Codex rollback branch id. `None` means main history.
 */
branch?: string, };
