// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DailySeries } from "./DailySeries";
import type { DateRange } from "./DateRange";
import type { DayBucket } from "./DayBucket";
import type { GroupBucket } from "./GroupBucket";
import type { HourlyActivity } from "./HourlyActivity";
import type { Totals } from "./Totals";

export type Metrics = { range: DateRange, totals: Totals, byDay: Array<DayBucket>, 
/**
 * Sorted by cost, descending.
 */
byProject: Array<GroupBucket>, 
/**
 * Sorted by cost, descending.
 */
byModel: Array<GroupBucket>, 
/**
 * Per-provider totals, sorted by cost; present only when multiple providers have data.
 */
byProvider?: Array<GroupBucket>, 
/**
 * Compact local-time activity for the selected sessions; avoids shipping message details.
 */
hourlyActivity?: Array<HourlyActivity>, 
/**
 * Sorted by total cost, descending.
 */
seriesByProvider?: Array<DailySeries>, 
/**
 * Sorted by total cost, descending.
 */
seriesByModel?: Array<DailySeries>, 
/**
 * Sorted by total cost, descending.
 */
seriesByProject?: Array<DailySeries>, };
