// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ScanError } from "./ScanError";
import type { SourceScan } from "./SourceScan";

/**
 * Progress or outcome of the latest scan of the provider's session directory.
 */
export type ScanReport = { sourceDir: string, 
/**
 * Last progress update or completion time as an RFC 3339 UTC timestamp.
 */
scannedAt: string, 
/**
 * Number of sessions successfully loaded into the cache.
 */
sessions: number, 
/**
 * Individual files that could not be read or parsed and were skipped.
 */
errors: Array<ScanError>, 
/**
 * True while providers are still being scanned; absent means a completed scan.
 */
scanning?: boolean, sources?: Array<SourceScan>, 
/**
 * Duplicate Codex threads found across homes and merged into one session.
 */
duplicatesMerged?: number, };
