// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Message } from "./Message";
import type { SessionSummary } from "./SessionSummary";
import type { Subagent } from "./Subagent";

export type SessionDetail = { summary: SessionSummary, messages: Array<Message>, subagents: Array<Subagent>, };
