// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CostBreakdown } from "./CostBreakdown";
import type { Provider } from "./Provider";
import type { Usage } from "./Usage";

/**
 * One row in the sessions list.
 */
export type SessionSummary = { id: string, provider: Provider, 
/**
 * Working directory the session ran in, e.g. `C:\Users\me\dev\app`.
 */
projectPath: string, 
/**
 * Stable grouping id derived from the repository origin or normalized path.
 */
projectKey: string, 
/**
 * Repository name or the last path segment, for display.
 */
projectName: string, 
/**
 * Codex home this session was read from.
 */
sourceDir?: string, 
/**
 * Title generated by the agent (`ai-title`), if any.
 */
title: string | null, 
/**
 * First user prompt, truncated to ~200 chars. Fallback when there is no title.
 */
firstPrompt: string | null, startedAt: string, endedAt: string, durationMs: number, 
/**
 * Distinct models used (no duplicates), most used first by token usage.
 */
models: Array<string>, gitBranch: string | null, cliVersion: string | null, 
/**
 * Includes messages from the main session and all subagents.
 */
messageCount: number, 
/**
 * Tool calls and errors include the main session and all subagents.
 */
toolCallCount: number, toolErrorCount: number, 
/**
 * Calls to `SessionFilter.tool` (main session plus subagents) for the active list filters.
 * Present only when `list_sessions` was called with a tool filter.
 */
filteredToolCalls?: number, 
/**
 * Errors among calls to `SessionFilter.tool`. Same presence rule.
 */
filteredToolErrors?: number, subagentCount: number, 
/**
 * Main session plus all subagents.
 */
usage: Usage, 
/**
 * Estimated cost in USD (main session plus subagents).
 */
costUsd: number, costBreakdown: CostBreakdown, 
/**
 * Tokens from models without a known price. Absent means zero.
 */
unpricedTokens?: number, };
