// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Provider } from "./Provider";

/**
 * Filters for `list_sessions`. Every field is optional; `None` means "no filter".
 */
export type SessionFilter = { provider?: Provider, 
/**
 * Exact match on `project_path`.
 */
projectPath?: string, 
/**
 * Exact match on the stable project identity.
 */
projectKey?: string, 
/**
 * Matches if the session used this model.
 */
model?: string, 
/**
 * Matches messages attributed to any of these models.
 */
models?: Array<string>, 
/**
 * Exact, case-sensitive tool name used by the session.
 */
tool?: string, 
/**
 * Inclusive range on the day of `started_at` in the machine's local timezone, as `YYYY-MM-DD`.
 */
from?: string, to?: string, 
/**
 * Local weekday (0 = Monday … 6 = Sunday).
 */
weekday?: number, 
/**
 * Local hour (0–23).
 */
hour?: number, 
/**
 * Case-insensitive substring over title, first prompt and project name.
 */
search?: string, };
