// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Provider } from "./Provider";
import type { ScanError } from "./ScanError";

/**
 * One provider's part of a scan.
 */
export type SourceScan = { provider: Provider, sourceDir: string, 
/**
 * False when the directory does not exist (provider not installed).
 */
available: boolean, sessions: number, errors: Array<ScanError>, scanning?: boolean, };
