// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CostBreakdown } from "./CostBreakdown";
import type { Message } from "./Message";
import type { Usage } from "./Usage";

export type Subagent = { id: string, 
/**
 * Subagent type, e.g. `Explore`, when known.
 */
agentType: string | null, 
/**
 * The `tool_use` id (in the parent session) that launched this subagent, when known.
 */
parentToolCallId: string | null, startedAt: string, endedAt: string, messages: Array<Message>, usage: Usage, costUsd: number, costBreakdown: CostBreakdown, 
/**
 * Tokens from models without a known price. Absent means zero.
 */
unpricedTokens?: number, };
