// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Token dimension used to scope token and cost metrics.
 */
export type TokenKind = "input" | "output" | "cacheRead" | "cacheWrite";
