// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CountBucket } from "./CountBucket";

export type ToolStat = { name: string, calls: number, errors: number, 
/**
 * `errors / calls`, 0..=1.
 */
errorRate: number, avgDurationMs: number | null, 
/**
 * Calls per project, descending.
 */
byProject: Array<CountBucket>, };
