// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * A tool invocation joined with its result.
 */
export type ToolCall = { id: string, name: string, input: JsonValue, 
/**
 * Result text, truncated to ~20 KB. `None` if no result was recorded.
 */
result: string | null, isError: boolean, 
/**
 * Time between the call and its result.
 */
durationMs: number | null, 
/**
 * Parent call id for nested calls, such as tools inside a Codex `exec`.
 */
parentCallId?: string, };
