// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CostBreakdown } from "./CostBreakdown";
import type { Usage } from "./Usage";

export type Totals = { sessions: number, messages: number, toolCalls: number, toolErrors: number, subagents: number, usage: Usage, costUsd: number, costBreakdown: CostBreakdown, activeMs: number, 
/**
 * Tokens from models without a known price. Absent means zero.
 */
unpricedTokens?: number, };
