// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Token usage. Counted once per API message (deduplicated by message id).
 */
export type Usage = { inputTokens: number, outputTokens: number, cacheReadTokens: number, cacheCreationTokens: number, 
/**
 * Reasoning tokens, already included in `output_tokens` (Codex only). Informational.
 */
reasoningTokens?: number, };
