//! Provider-agnostic data model shared with the frontend.
//!
//! This is the contract between backend and frontend: every type here is
//! exported to TypeScript (`src/bindings/`) with `cargo test export_bindings`.
//! Change it deliberately and regenerate the bindings in the same commit.
//!
//! Conventions:
//! - Timestamps are RFC 3339 strings in UTC (`2026-10-05T15:39:06.436Z`).
//! - Days are `YYYY-MM-DD` in the machine's local timezone.
//! - Token counts are `u64` in Rust and `number` in TypeScript.

use serde::{Deserialize, Serialize};
use ts_rs::TS;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize, TS)]
#[serde(rename_all = "lowercase")]
#[ts(export)]
pub enum Provider {
    Claude,
    Codex,
}

/// Token dimension used to scope token and cost metrics.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub enum TokenKind {
    Input,
    Output,
    CacheRead,
    CacheWrite,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "lowercase")]
#[ts(export)]
pub enum Role {
    User,
    Assistant,
}

/// Token usage. Counted once per API message (deduplicated by message id).
#[derive(Debug, Clone, Copy, Default, PartialEq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct Usage {
    #[ts(type = "number")]
    pub input_tokens: u64,
    #[ts(type = "number")]
    pub output_tokens: u64,
    #[ts(type = "number")]
    pub cache_read_tokens: u64,
    #[ts(type = "number")]
    pub cache_creation_tokens: u64,
    /// Reasoning tokens, already included in `output_tokens` (Codex only). Informational.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[ts(optional, type = "number")]
    pub reasoning_tokens: Option<u64>,
}

/// Estimated USD cost split by token kind; parts sum to the matching cost_usd.
#[derive(Debug, Clone, Copy, Default, PartialEq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct CostBreakdown {
    pub input: f64,
    pub output: f64,
    pub cache_read: f64,
    pub cache_write: f64,
}

/// One row in the sessions list.
#[derive(Debug, Clone, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct SessionSummary {
    pub id: String,
    pub provider: Provider,
    /// Working directory the session ran in, e.g. `C:\Users\me\dev\app`.
    pub project_path: String,
    /// Stable grouping id derived from the repository origin or normalized path.
    pub project_key: String,
    /// Repository name or the last path segment, for display.
    pub project_name: String,
    /// Codex home this session was read from.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[ts(optional)]
    pub source_dir: Option<String>,
    /// Title generated by the agent (`ai-title`), if any.
    pub title: Option<String>,
    /// First user prompt, truncated to ~200 chars. Fallback when there is no title.
    pub first_prompt: Option<String>,
    pub started_at: String,
    pub ended_at: String,
    #[ts(type = "number")]
    pub duration_ms: u64,
    /// Distinct models used (no duplicates), most used first by token usage.
    pub models: Vec<String>,
    pub git_branch: Option<String>,
    pub cli_version: Option<String>,
    /// Includes messages from the main session and all subagents.
    pub message_count: u32,
    /// Tool calls and errors include the main session and all subagents.
    pub tool_call_count: u32,
    pub tool_error_count: u32,
    /// Calls to `SessionFilter.tool` (main session plus subagents) for the active list filters.
    /// Present only when `list_sessions` was called with a tool filter.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[ts(optional)]
    pub filtered_tool_calls: Option<u32>,
    /// Errors among calls to `SessionFilter.tool`. Same presence rule.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[ts(optional)]
    pub filtered_tool_errors: Option<u32>,
    pub subagent_count: u32,
    /// Main session plus all subagents.
    pub usage: Usage,
    /// Estimated cost in USD (main session plus subagents).
    pub cost_usd: f64,
    pub cost_breakdown: CostBreakdown,
    /// Tokens from models without a known price. Absent means zero.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[ts(optional, type = "number")]
    pub unpriced_tokens: Option<u64>,
}

#[derive(Debug, Clone, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct SessionDetail {
    pub summary: SessionSummary,
    pub messages: Vec<Message>,
    pub subagents: Vec<Subagent>,
}

#[derive(Debug, Clone, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct Subagent {
    pub id: String,
    /// Subagent type, e.g. `Explore`, when known.
    pub agent_type: Option<String>,
    /// The `tool_use` id (in the parent session) that launched this subagent, when known.
    pub parent_tool_call_id: Option<String>,
    pub started_at: String,
    pub ended_at: String,
    pub messages: Vec<Message>,
    pub usage: Usage,
    pub cost_usd: f64,
    pub cost_breakdown: CostBreakdown,
    /// Tokens from models without a known price. Absent means zero.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[ts(optional, type = "number")]
    pub unpriced_tokens: Option<u64>,
}

#[derive(Debug, Clone, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct Message {
    pub id: String,
    pub role: Role,
    pub timestamp: String,
    /// Model that produced the message (assistant only).
    pub model: Option<String>,
    pub blocks: Vec<Block>,
    /// Usage of this API message (assistant only).
    pub usage: Option<Usage>,
    /// Discarded Codex rollback branch id. `None` means main history.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[ts(optional)]
    pub branch: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, TS)]
#[serde(tag = "type", rename_all = "camelCase")]
#[ts(export)]
pub enum Block {
    Text { text: String },
    Thinking { text: String },
    ToolCall(ToolCall),
}

/// A tool invocation joined with its result.
#[derive(Debug, Clone, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct ToolCall {
    pub id: String,
    pub name: String,
    pub input: serde_json::Value,
    /// Result text, truncated to ~20 KB. `None` if no result was recorded.
    pub result: Option<String>,
    pub is_error: bool,
    /// Time between the call and its result.
    #[ts(type = "number | null")]
    pub duration_ms: Option<u64>,
    /// Parent call id for nested calls, such as tools inside a Codex `exec`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[ts(optional)]
    pub parent_call_id: Option<String>,
}

/// Filters for `list_sessions`. Every field is optional; `None` means "no filter".
#[derive(Debug, Clone, Default, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase", default)]
#[ts(export, optional_fields)]
pub struct SessionFilter {
    pub provider: Option<Provider>,
    /// Exact match on `project_path`.
    pub project_path: Option<String>,
    /// Exact match on the stable project identity.
    pub project_key: Option<String>,
    /// Matches if the session used this model.
    pub model: Option<String>,
    /// Matches messages attributed to any of these models.
    pub models: Option<Vec<String>>,
    /// Exact, case-sensitive tool name used by the session.
    pub tool: Option<String>,
    /// Inclusive range on the day of `started_at` in the machine's local timezone, as `YYYY-MM-DD`.
    pub from: Option<String>,
    pub to: Option<String>,
    /// Local weekday (0 = Monday … 6 = Sunday).
    pub weekday: Option<u8>,
    /// Local hour (0–23).
    pub hour: Option<u8>,
    /// Case-insensitive substring over title, first prompt and project name.
    pub search: Option<String>,
}

/// Inclusive day range in the machine's local timezone, `YYYY-MM-DD`. `None` means unbounded.
#[derive(Debug, Clone, Default, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase", default)]
#[ts(export, optional_fields)]
pub struct DateRange {
    pub from: Option<String>,
    pub to: Option<String>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct Totals {
    pub sessions: u32,
    pub messages: u32,
    pub tool_calls: u32,
    pub tool_errors: u32,
    pub subagents: u32,
    pub usage: Usage,
    pub cost_usd: f64,
    pub cost_breakdown: CostBreakdown,
    #[ts(type = "number")]
    pub active_ms: u64,
    /// Tokens from models without a known price. Absent means zero.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[ts(optional, type = "number")]
    pub unpriced_tokens: Option<u64>,
}

#[derive(Debug, Clone, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct DayBucket {
    /// `YYYY-MM-DD`. Every day in the range is present, including empty ones.
    pub date: String,
    pub sessions: u32,
    pub tool_calls: u32,
    /// Tool calls that ended in error that day. Absent means zero.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[ts(optional)]
    pub tool_errors: Option<u32>,
    pub usage: Usage,
    pub cost_usd: f64,
    pub cost_breakdown: CostBreakdown,
    /// Tokens from models without a known price. Absent means zero.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[ts(optional, type = "number")]
    pub unpriced_tokens: Option<u64>,
}

/// One day in a compact, message-attributed daily series.
#[derive(Debug, Clone, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct DayPoint {
    /// `YYYY-MM-DD` in the machine's local timezone.
    pub date: String,
    pub cost_usd: f64,
    #[ts(type = "number")]
    pub tokens: u64,
    #[ts(type = "number")]
    pub active_ms: u64,
    pub sessions: u32,
    pub tool_calls: u32,
    /// Tool calls that ended in error that day. Absent means zero.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[ts(optional)]
    pub tool_errors: Option<u32>,
    pub messages: u32,
}

/// A precomputed daily series for a provider, model, or project.
#[derive(Debug, Clone, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct DailySeries {
    pub key: String,
    pub label: String,
    /// Only days with data, sorted by date.
    pub points: Vec<DayPoint>,
}

#[derive(Debug, Clone, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct GroupBucket {
    /// Grouping key: project path, model id, etc.
    pub key: String,
    /// Human label (e.g. project name).
    pub label: String,
    pub sessions: u32,
    pub usage: Usage,
    pub cost_usd: f64,
    pub cost_breakdown: CostBreakdown,
    /// Tokens from models without a known price. Absent means zero.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[ts(optional, type = "number")]
    pub unpriced_tokens: Option<u64>,
}

/// Compact message and session counts for each local weekday/hour cell.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct HourlyActivity {
    /// Monday is 0 and Sunday is 6.
    pub weekday: u8,
    pub hour: u8,
    pub messages: u32,
    /// Distinct sessions with at least one message in this cell.
    pub sessions: u32,
}

#[derive(Debug, Clone, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct Metrics {
    pub range: DateRange,
    pub totals: Totals,
    pub by_day: Vec<DayBucket>,
    /// Sorted by cost, descending.
    pub by_project: Vec<GroupBucket>,
    /// Sorted by cost, descending.
    pub by_model: Vec<GroupBucket>,
    /// Per-provider totals, sorted by cost; present only when multiple providers have data.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[ts(optional)]
    pub by_provider: Option<Vec<GroupBucket>>,
    /// Compact local-time activity for the selected sessions; avoids shipping message details.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[ts(optional)]
    pub hourly_activity: Option<Vec<HourlyActivity>>,
    /// Sorted by total cost, descending.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[ts(optional)]
    pub series_by_provider: Option<Vec<DailySeries>>,
    /// Sorted by total cost, descending.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[ts(optional)]
    pub series_by_model: Option<Vec<DailySeries>>,
    /// Sorted by total cost, descending.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[ts(optional)]
    pub series_by_project: Option<Vec<DailySeries>>,
}

/// Progress or outcome of the latest scan of the provider's session directory.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct ScanReport {
    pub source_dir: String,
    /// Last progress update or completion time as an RFC 3339 UTC timestamp.
    pub scanned_at: String,
    /// Number of sessions successfully loaded into the cache.
    pub sessions: u32,
    /// Individual files that could not be read or parsed and were skipped.
    pub errors: Vec<ScanError>,
    /// True while providers are still being scanned; absent means a completed scan.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[ts(optional)]
    pub scanning: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[ts(optional)]
    pub sources: Option<Vec<SourceScan>>,
    /// Duplicate Codex threads found across homes and merged into one session.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[ts(optional, type = "number")]
    pub duplicates_merged: Option<u32>,
}

/// One provider's part of a scan.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct SourceScan {
    pub provider: Provider,
    pub source_dir: String,
    /// False when the directory does not exist (provider not installed).
    pub available: bool,
    pub sessions: u32,
    pub errors: Vec<ScanError>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[ts(optional)]
    pub scanning: Option<bool>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct ScanError {
    pub path: String,
    pub message: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[ts(optional)]
    pub provider: Option<Provider>,
}

#[derive(Debug, Clone, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct CountBucket {
    pub key: String,
    pub label: String,
    pub count: u32,
}

#[derive(Debug, Clone, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct ToolStat {
    pub name: String,
    pub calls: u32,
    pub errors: u32,
    /// `errors / calls`, 0..=1.
    pub error_rate: f64,
    #[ts(type = "number | null")]
    pub avg_duration_ms: Option<u64>,
    /// Calls per project, descending.
    pub by_project: Vec<CountBucket>,
}

/// Error returned to the frontend by every command.
#[derive(Debug, Clone, Serialize, TS, thiserror::Error)]
#[serde(tag = "kind", content = "message", rename_all = "camelCase")]
#[ts(export)]
pub enum AppError {
    #[error("not found: {0}")]
    NotFound(String),
    #[error("io error: {0}")]
    Io(String),
    #[error("not implemented: {0}")]
    NotImplemented(String),
}
